version: 2

models:
  - name: dim_google_poi
    description: "POI dimension table (one row per place_id)."
    columns:
      - name: place_id
        description: "Google Place ID."
        tests:
          - not_null
          - unique

  - name: fact_google_poi
    description: "POI fact table (metrics captured at fetched_at)."
    columns:
      - name: place_id
        description: "Google Place ID."
        tests:
          - not_null
          - relationships:
              to: ref('dim_google_poi')
              field: place_id
